### ISSUE TITLE
error with alexa sync list

### ISSUE THREAD

**Issue by shedman214** [SavageCore/HA_Addons#31]
when i add any item to my HA shopping list. I get this error in the logs 
![image](https://github.com/user-attachments/assets/92244f01-ebc1-4e50-afcb-5974a688a91d)

**Comment by SavageCore** [comment]
Looks like you have issues on the login step. What are your urls set to?

**Comment by shedman214** [comment]
![Image](https://github.com/user-attachments/assets/7b561c3d-bccc-4180-b3cd-fffd5a68a711)

This is my rest automation error also

**Comment by SavageCore** [comment]
Please provide me the full login url as text, the screenshot is cutoff

**Comment by shedman214** [comment]
> Please provide me the full login url as text, the screenshot is cutoff

https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fhz%2Fwishlist%2Fintro%3Fref_%3Dnav_ya_signin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=usflex&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0

**Comment by shedman214** [comment]
@SavageCore  any update?

**Comment by kellerassel007** [comment]
I had the same error when using my Amazon login url for Germany. I found the issue, it was because my login url used language=de_DE parameter and this addon seems to only work when language is explicitely set to language=en_GB in login_url.

So I added it to your URL provided and this login_url should work for you:
https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fhz%2Fwishlist%2Fintro%3Fref_%3Dnav_ya_signin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=usflex&openid.mode=checkid_setup**&language=en_GB**&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0

**Comment by shedman214** [comment]
```
[2025-03-15 08:25:49 -0500] [85] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[08:26:25] INFO: Starting Alexa Shopping List Sync
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /app/main.py:274> exception=NoSuchElementException()>
Traceback (most recent call last):
  File "/app/main.py", line 275, in main
    await login(driver)
  File "/app/main.py", line 69, in login
    mfa_code_input = driver.find_element(By.ID, "auth-mfa-otpcode")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/seleniumbase/core/sb_driver.py", line 27, in find_element
    return self.driver.default_find_element(by=by, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="auth-mfa-otpcode"]"}
  (Session info: chrome=131.0.6778.264); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
[2025-03-15 08:26:58 -0500] [85] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
```

**Comment by shedman214** [comment]
> I had the same error when using my Amazon login url for Germany. I found the issue, it was because my login url used language=de_DE parameter and this addon seems to only work when language is explicitely set to language=en_GB in login_url.
> 
> So I added it to your URL provided and this login_url should work for you: https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fhz%2Fwishlist%2Fintro%3Fref_%3Dnav_ya_signin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=usflex&openid.mode=checkid_setup&language=en_GB&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
> 
> Technical reason is probably that selenium looks for specific field names for login mask and these are different names in different languages, so it can't find the login fields.

```
[2025-03-15 08:25:49 -0500] [85] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[08:26:25] INFO: Starting Alexa Shopping List Sync
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /app/main.py:274> exception=NoSuchElementException()>
Traceback (most recent call last):
  File "/app/main.py", line 275, in main
    await login(driver)
  File "/app/main.py", line 69, in login
    mfa_code_input = driver.find_element(By.ID, "auth-mfa-otpcode")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/seleniumbase/core/sb_driver.py", line 27, in find_element
    return self.driver.default_find_element(by=by, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="auth-mfa-otpcode"]"}
  (Session info: chrome=131.0.6778.264); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
[2025-03-15 08:26:58 -0500] [85] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
```

**Comment by kellerassel007** [comment]
Did you enable two factor authentication for your Amazon account like described in documentation?

**Comment by shedman214** [comment]
> Did you enable two factor authentication for your Amazon account like described in documentation?

Yes I did. i followed all the steps
