### ISSUE TITLE
No Items sync - Error with NoneType object

### ISSUE THREAD

**Issue by RocketKuhr** [SavageCore/HA_Addons#9]
Hi,

i didn´t get some items in my HA-shopping list. After setting up the configuration I statarted the AddOn (on x86 installation on IntelNuc). I get this out of the protocol tab:

[13:48:21] INFO: Starting Alexa Shopping List Sync
[2024-09-02 13:48:38 +0200] [85] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
[2024-09-02 13:48:38,757] [ERROR] An error occurred while fetching items: Failed to get items: {'code': 'home_assistant_error', 'message': 'Service call requested response data but did not match any entities'}
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /app/main.py:271> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "/app/main.py", line 274, in main
    await update_local_shopping_list(driver, config)
  File "/app/main.py", line 101, in update_local_shopping_list
    existing_item_names = [item["summary"].lower() for item in existing_items]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by SavageCore** [comment]
Thanks for spotting that error when HA list is empty. Fix incoming!

**Comment by RocketKuhr** [comment]
sorry, I updated the addon and get nearly same error, different line. You need something more for debugging?


[06:39:16] INFO: Starting Alexa Shopping List Sync
[2024-09-03 06:39:23 +0200] [85] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
[2024-09-03 06:39:24,669] [ERROR] An error occurred while fetching items: Failed to get items: {'code': 'home_assistant_error', 'message': 'Service call requested response data but did not match any entities'}
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /app/main.py:274> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "/app/main.py", line 277, in main
    await update_local_shopping_list(driver, config)
  File "/app/main.py", line 101, in update_local_shopping_list
    existing_item_names = [item["summary"].lower() for item in existing_items]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by SavageCore** [comment]
Oh my bad, try the new version going live now!

**Comment by RocketKuhr** [comment]
thanks, this message is solved. But get an new one :-)
I will create a new issue. Many thanks for your help!
